package projecteuler.problems;

/**
 * 
 * @author Tarcisio
 * 
 *         Project Euler Problem 2 - http://projecteuler.net/problem=2
 * 
 *         Each new term in the Fibonacci sequence is generated by adding the
 *         previous two terms. By starting with 1 and 2, the first 10 terms will
 *         be:
 * 
 *         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 *         By considering the terms in the Fibonacci sequence whose values do
 *         not exceed four million, find the sum of the even-valued terms.
 *         
 */
public class Problem2 implements Problem {

	@Override
	public int solve() {
		int count = 2;
		int n1 = 1;
		int n2 = 2;
		int temp = 0;
		boolean flag = true;

		while (flag) {
			temp = n2;
			n2 = n1 + n2;
			n1 = temp;

			if (n2 % 2 == 0) {
				if (n2 + count > 4000000) {
					flag = false;
				}
				count += n2;
			}
		}
		return count;
	}
}
